<?php
/**
 * Created by PhpStorm.
 * User: Lu.Chen
 * Date: 2018/8/20
 * Time: 11:09
 */
namespace frontend\models;

class UserPoetry extends \common\models\UserPoetry
{
    public function beforeSave($insert)
    {

        $this->create_at = date('YmdHis');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    //取用户近30天 阅读过的诗词ID
    public function recentPoetryId($userId)
    {
        $date = strtotime('Ymd', time()-30*24*3600);
        $idAll = self::find()->select('poetry_id')
            ->where(['=','user_id',$userId])
            ->andWhere([ '>=','date', $date])
            ->all();
        $idList = array_column($idAll, 'poetry_id');

        return $idList;
    }

    public function todayPoetry($userId)
    {



    }


}